<form method="post" action="<?=$this->action?>/">
    <div class="hint">Тема:</div>
    <input type="text" placeholder="Тема" name="title" value="<?=$this->post->getTitle()?>" /><br/>
    <div class="hint">Сообщение:</div>
    <textarea name="body" placeholder="Сообщение"><?=$this->post->getBody()?></textarea><br/>
    <div class="hint">Теги через запятую:</div>
    <input type="text" placeholder="Теги через запятую" name="tags" value="<?=$this->postTags?>" /><br/>
    <div class="hint">Доп. материал ссылкой (изображение или видео):</div>
    <input type="text" placeholder="Url изображения или видео" name="extra" value="<?=$this->post->getExtra()?>" /><br/>
    <input type="submit" value="<?=$this->buttonLabel?>" />
    <?if($error = View::getThroughData("error")):?>
        <div class="error"><?=$error?></div>
    <?endif;?>
</form> 